### ISSUE TITLE
Layers tab Scroll bar

### ISSUE THREAD

**Issue by Willsm50** [juliandescottes/piskel#501] opened 2016-07-10 07:09 UTC
Hi, I start animating with piskel using multiple layer. the problem is, when the layers amount increase, Transform & palletes tabs are pulling down too. Perhaps adding scroll bar to layers tab might fix this problem.

**Comment by juliandescottes** [comment] 2016-07-10 10:52
Hi, I think this is a duplicate of #467 

Will be fixed when 0.8.0 is released.

**Comment by Willsm50** [comment] 2016-07-10 15:55
Hi, Oh, sorry about that. Thanks for answering my question.

**Comment by juliandescottes** [comment] 2016-07-10 16:15
no worries at all! 

v0.8.0 has just been released, so feel free to test it and check if we were thinking about the same issue.

**Comment by Willsm50** [comment] 2016-07-10 17:50
![bug](https://cloud.githubusercontent.com/assets/20373335/16715085/d415b4dc-4700-11e6-9aed-252a33195b5c.png)
![bug2](https://cloud.githubusercontent.com/assets/20373335/16715096/09e6e64e-4701-11e6-86d6-dec1d504dec1.png)
Hi! I just test it. There's issue with color tab now. It won't display if layer & color palletes are much.

**Comment by juliandescottes** [comment] 2016-07-10 19:14
Looks like this issue is specific to the offline version, might be linked to the chrome version embedded by the node-webkit build :/ 

Tried with a newer version and reuploaded here: https://dl.dropboxusercontent.com/u/17803671/piskel/standalone/mac/Piskel-0.8.0.dmg 

Let me know if you can give it a try.

**Comment by Willsm50** [comment] 2016-07-10 19:34
Sorry, but im not using OS X, Is there any windows version?

**Comment by juliandescottes** [comment] 2016-07-11 08:32
Ah sorry about that, will upload a new windows version as soon as I can !

**Comment by juliandescottes** [comment] 2016-07-26 12:54
Forgot to update the issue! Windows and Linux versions have been released @Willsm50 could you give them a shot?

**Comment by juliandescottes** [comment] 2016-08-15 23:15
Should be good, please reopen if needed.

**Closed by juliandescottes** 2016-08-15 23:15 UTC
