### ISSUE TITLE
Single undo clears dirty asterisk

### ISSUE THREAD

**Issue by epicabsol** [juliandescottes/piskel#447] opened 2016-04-12 01:18 UTC
To reproduce, create a piskel and draw a few things. After a singular undo (Ctrl+Z), the asterisk signifying that there are unsaved changes is removed from the in-editor title bar, and if closed, the editor will exit without asking to save changes. It is still possible to continue undo-ing previous actions.

**Comment by juliandescottes** [comment] 2016-04-12 08:09
Thanks for the report! 

The issue is probably with the SavedStatusService, which tries to put a flag on the current Piskel instance to know whether or not it was saved. This will fail everytime the current piskel is replaced with a new Piskel instance:
- when undoing
- when resizing 
- when importing

The current implementation is quite buggy. It would probably be better to do the following:
- generate UUIDs for each state in the HistoryService
- in SavedStatusService, listen to the PISKEL_SAVED event and store the current state UUID 
- in SavedStatusService::isDirty way we can easily compare the saved state to the current state

**Comment by juliandescottes** [comment] 2016-05-22 13:11
Fixed, will be released with v0.8.0

**Closed by juliandescottes** 2016-05-22 13:11 UTC
Labels: difficulty:easy, priority:3, status:confirmed, type:bug
