### ISSUE TITLE
Exporting a Piskel and Importing the Same File Changes its Color Palette

### ISSUE THREAD

**Issue by PaperPlayerX** [juliandescottes/piskel#631] opened 2017-02-02 23:52 UTC
If I export a file in Piskel, then import the same file again, all of the colors appear to darken or change saturation slightly (can't tell which).

Steps to reproduce the bug:
1. Go to piskelapp.com
2. Create any sprite with any distinct color
3. Export it
4. Import the same file

Environment details:
Operating system: Windows 10
Browser: Firefox

Sprite details:
1 frame, any resolution, session duration doesn't seem to affect anything.

**Comment by juliandescottes** [comment] 2017-02-03 00:17
Thanks for filing.

I can't reproduce for now, using firefox on Windows 7, so we'll need additional details to investigate:
- can you also say which export you are using? Are you using .piskel, .png, .gif ?
- chromebook users reported similar issues but it looks like you're running this on a regular OS. Your machine specs could still be relevant here if you don't mind sharing them.
- can you share a sprite with which you have the issue? Rename the .piskel as .txt if Github complains about the import
- can you share some screenshots to illustrate the issue

Thanks

**Comment by juliandescottes** [comment] 2017-02-06 00:07
@PaperPlayerX any feedback ?

**Comment by juliandescottes** [comment] 2017-02-23 18:07
Closing for now, please reopen if needed.

**Closed by juliandescottes** 2017-02-23 18:07 UTC
Labels: unconfirmed
