### ISSUE TITLE
Layers and preview

### ISSUE THREAD

**Issue by AlexHolly** [juliandescottes/piskel#312] opened 2015-09-20 20:41 UTC
The preview shows all layers even the hidden. Is that a bug?

**Comment by juliandescottes** [comment] 2015-09-20 22:36
Hi,

Which preview are you talking about ? The frame list ? The animated preview ?

The animated preview on the right always shows all layers.

I don't know what you mean by hidden layer ? Are you referring to the layer opacity slider from the preferences ? It only affects the main drawing area. 

Can you please give more details about the issue you are facing ? A screenshot would help :)

Thanks !

**Comment by AlexHolly** [comment] 2015-09-20 22:49
Yes i mean the animation preview on the top right.
So when i hide a layer(the eye icon) it shows that layer in the animation preview. 
You already said that it always shows all layers. So it is not a bug...

**Comment by juliandescottes** [comment] 2015-09-21 05:30
Not a bug, but maybe the wording is confusing. 

The eye icon is a global toggle to view all layers in the main drawing area. What you want is a way to hide a specific layer, which would be nice but not available for now. 

Thanks for the feedback ! Keeping this open to review the labels of the eye toggle tooltip and of the layer opacity settings

**Comment by juliandescottes** [comment] 2015-10-07 22:53
Updated tooltip to be less confusing :  

![New layer preview tooltip](https://screenletstore.appspot.com/img/1630f719-6d46-11e5-bce7-4d8c556c5b72.png)

Closing the issue.

**Closed by juliandescottes** 2015-10-07 22:53 UTC
