### ISSUE TITLE
Feature request: support for command-line arguments in nwjs app

### ISSUE THREAD

**Issue by tlm-2501** [juliandescottes/piskel#661] opened 2017-04-13 15:44 UTC
Currently, if you supply a command-line argument, be it a path to a .piskel file, or a .png, or whatever, Piskel does absolutely nothing -- it doesn't even start. This isn't acceptable behaviour. What should happen is something along these lines: if a path to a .piskel file is supplied as an argument, it should be loaded in the editor directly. Otherwise, if a path to another format supported for import is supplied (.png, .gif...), the import dialogue should open with that file selected, and it should prompt for the rest of the settings (e.g. sprite width/height, etc). Finally, if a path to an unsupported file format is specified, an error box should pop up.

**Comment by juliandescottes** [comment] 2017-04-13 15:55
This is a duplicate of issue #596 , so I'm closing this one.

The limitation seems to be coming from nwjs. According to the nwjs issues linked in the other bug, it looks like the latest version might be improving the situation there.

**Closed by juliandescottes** 2017-04-13 15:55 UTC
