### ISSUE TITLE
[BUG] Color replace tool

### ISSUE THREAD

**Issue by AlexHolly** [juliandescottes/piskel#332] opened 2015-11-05 21:02 UTC
Sometimes the "color replace tool" is not replacing all areas of the same color.
I used the color picker and he tells me it's the same color.

After "save to gallery" and reopen(edit) the sprite the "color replace tool" works as expected.
  Save as .piskel and reopen has the same effect.

**Comment by juliandescottes** [comment] 2015-11-06 00:32
I think I fixed it with commit 573d7ca0517e96198c94f49d0f7c90d98f2ddd5d , which will be released with 0.6.0.

If you have a reproducible scenario, I can test it against this fix ?

**Comment by AlexHolly** [comment] 2015-11-06 09:09
It's hard to reproduce I try to explain.
So it looks like the problem has to do with the palett on the bottom right sometimes it adds the same color twice to the palett. They have the same color value but when you use the "color replace tool"
it acts like the colors are different.

The master branch has also that bug.

1. Pick a color(Primary Left)  #ff0000
2. Draw with the Pencil tool a few pixels
3. Select the new color from the palett bottom right.
4. draw with this color they are different,
5. try to use the replace tool.

So I think I see the difference one color has #FF0000 and the other is #ff0000 maybe the equals is not working properly.

**Comment by juliandescottes** [comment] 2015-11-06 09:14
Perfect. That's precisely what I fixed so we should be good !

Thanks for the detailed info.

**Comment by juliandescottes** [comment] 2015-11-06 10:01
Cannot reproduce on master branch.

**Comment by AlexHolly** [comment] 2015-11-06 10:16
Hmm you are right now it works I don't know why. Let's close it for now we will see if it comes back.

**Comment by AlexHolly** [comment] 2015-11-06 10:19
hahah... now it happens again I dont' get it the problem is that it is still adding two colors to the pallet on the bottom right.

**Comment by juliandescottes** [comment] 2015-11-06 10:23
Ok let's keep this open. If still can't reproduce it, so if you find another scenario please share it here.

Thanks !

**Comment by AlexHolly** [comment] 2015-11-06 10:30
Can you add the colors to the palett with lower case? Somehow I got one with upper and one with lower case inside the palett I don't know how. It will also fix a small bug with the color picker where the color is not beeing selected on the bottom right palett. So if the colors are all in lower case in the palett it will also fix the other bug.

**Comment by juliandescottes** [comment] 2015-11-06 10:34
Good point, I'll take the opportunity to review the different places in th

**Comment by juliandescottes** [comment] 2015-11-27 22:04
Colors should now always be using the following format before being stored in a Frame object : 
"#[a-f0-9]{6}" (hex string lowercase).

**Comment by juliandescottes** [comment] 2015-11-27 22:05
PR #343 merged.

**Closed by juliandescottes** 2015-11-27 22:05 UTC
Labels: issue
