### ISSUE TITLE
Desktop client hangs on copy/paste

### ISSUE THREAD

**Issue by dosjos** [juliandescottes/piskel#270] opened 2015-04-16 08:52 UTC
Often when I use the desktop client the editor hangs when i use the copy/paste functions.

The GUI becomes unresponsive and the mouse cursor have the hand symbol.
Sometimes it unfreezes after a few seconds, other times I have waited several minutes before restarting because it does not unfreeze.

Using Piskel 0.4.2
Windows 8.1

**Comment by juliandescottes** [comment] 2015-04-16 09:18
Can you share the dimension of the sprite you are editing ? Size, layers etc ...
Does it happen as soon as you start using copy/paste, or only after some time using the application.

Thanks !

**Comment by dosjos** [comment] 2015-04-16 09:55
Hi

The sprite is 64x64, It did hang the most on the fouth layer (of five).
Copying from layer 3 to 4.

You can find the piskel file here: https://onedrive.live.com/redir?resid=954a1f610664c227!515&authkey=!ADffaJ78rY9dHWI&ithint=file%2cpiskel
![wall2](https://cloud.githubusercontent.com/assets/609086/7178481/6d543104-e42f-11e4-9b19-06a3a94a66fe.png)

**Comment by juliandescottes** [comment] 2015-04-16 10:19
Thanks for sharing the sprite. 
So far I'm unable to reproduce the issue (testing on Piskel 0.4.2 with Window 8.1).

I will need more information to investigate. 
Do you have an exact scenario that triggers the crash ? Starting point should be loading the piskel file you provided.

Could you share your computer specs as well ?

**Comment by dosjos** [comment] 2015-04-16 10:34
At the momen I am unable to replicate the bug.
But it mainly happened when I copied from one layer to the next.

Computer specs are:
Windows 8.1 pro 64bit
I7-2760QM 2.4 Ghz 8cpus
16GB ram
Directx 11
Dell latitude E6420

Also, unrelated question. Why isn't there a new piskel button in the app like there is in the webapp?

**Comment by juliandescottes** [comment] 2015-04-17 07:03
Thanks for the specifications, I don't see anything fishy about them :( 

Regarding the 'new pisklel' button, I just didn't think a lot about this. 
It's easy to integrate in the webapp because I can just open a new tab with a blank sprite. 

In the desktop version I guess I could just display a warning if there are unsaved changes, and replace the current sprite with a blank one.

**Comment by fsvieira** [comment] 2015-04-17 09:15
Hi, I am not sure but if you open a link on nodewebkit with target _blank I think it will open a new nodewebkit window.

**Comment by juliandescottes** [comment] 2015-04-17 09:22
@fsvieira Thanks for the info, I'll try it !

**Comment by juliandescottes** [comment] 2015-08-31 21:50
Fixed a bug related to copy paste issues when going out of the canvas limits.

I close this one for now, since we have not found a reproducible scenario :(

**Closed by juliandescottes** 2015-08-31 21:50 UTC
Labels: issue
