### ISSUE TITLE
Can't change brush size

### ISSUE THREAD

**Issue by Wakintosh** [juliandescottes/piskel#340] opened 2015-11-22 15:13 UTC
I love this program, but i can't seem to find a way to change the brush size for the pen tool, please help

**Comment by juliandescottes** [comment] 2015-11-22 20:34
Hi, this issue is a duplicate of #258 .

Implementation is ongoing, feel free to add your comments in the existing thread.

**Closed by juliandescottes** 2015-11-22 20:34 UTC
