### ISSUE TITLE
Gray sceen bug.

### ISSUE THREAD

**Issue by TheNetherrackAxe** [juliandescottes/piskel#664] opened 2017-04-18 23:04 UTC
Bug description
Whenever I go to zoom in past the vertical drawing space borders when editing a sprite, the drawing area becomes completely covered in a light gray box. I have looked at all of my settings, and I think it may be a bug. It makes it very difficult to do work on large sprite sheets.

### Steps to reproduce the bug
1. go to piskelapp.com
2. open any sprite
3. zoom in past vertical borders

### Environment details
* operating system: Chromebook OS
* browser (or offline application version): Google Chrome

### Sprite details
* number of frames: any
* sprite resolution: any
* session duration: instant

![screenshot 2017-04-18 at 7 12 46 pm](https://cloud.githubusercontent.com/assets/27745941/25156807/0ce15242-246b-11e7-8c93-72c10b65e73e.png)

**Comment by juliandescottes** [comment] 2017-04-18 23:33
Thanks for filing.

Sadly I think this is a duplicate of issue #651 , which is specific to Chromebooks and should normally go away with Chrome 58 (expected to be released in a 1-2 weeks)

I personally don't own a Chromebook so I can't investigate the issue. I anybody has the necessary hardware and is willing to work on that, help would really be appreciated!

Closing as duplicate, let's continue the discussion on #651

**Closed by juliandescottes** 2017-04-18 23:33 UTC

**Comment by TheNetherrackAxe** [comment] 2017-04-19 02:23
Ah, ok. Thanks for listening!
