### ISSUE TITLE
Issue : Uncaught node.js Error (cannot check current palette in CurrentColorsService)

### ISSUE THREAD

**Issue by Dullgarian** [juliandescottes/piskel#253] opened 2015-03-07 22:31 UTC
I have this error when I draw and release the mouse button. On Windows 7 64bits.

Uncaught node.js Error 

TypeError: Cannot read property 'id' of null
    at a.CurrentColorsService.isCurrentColorsPaletteSelected_ (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:13:1778)
    at a.CurrentColorsService.onPiskelUpdated_ (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:13:1526)
    at Object.$.event.dispatch (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:2:5581)
    at Object.g.handle.h (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:2:1588)
    at Object.$.event.trigger (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:2:4126)
    at Object.eval (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:2:11963)
    at Function.$.extend.each (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:1:14315)
    at $.fn.$.each (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:1:11034)
    at $.fn.extend.trigger (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:2:11939)
    at Function.a.publish (file:///C:/Users/MYNAME/AppData/Local/Temp/nw4140_8958/dest/js/piskel-packaged-min-2015-01-23-11-12.js:5:844)

**Comment by juliandescottes** [comment] 2015-03-08 00:03
Looks like something's wrong with your current palette. Do you have any
palette selected ?

I will modify this part of the code to make it more robust of course, but I
would like to understand how this could happen first :)

Could you upload a screenshot of your UI as well?

Thanks !

**Comment by Dullgarian** [comment] 2015-03-08 00:51
I don't understand why but now it's working flawlessly! I clicked under the palette menu on "current colors" and it worked! I think there was "no palette selected" or something like that as default but I can be wrong! It's disappeared, I can't repeat the error lol!

**Comment by juliandescottes** [comment] 2015-03-09 14:12
Glad you found a workaround. I will try to reproduce this myself before closing the issue.

Some questions if you have time : 
- did you create any palette yourself ?
- did you open two windows of the Piskel application at the same time ?

**Comment by Dullgarian** [comment] 2015-03-28 02:40
Sorry for the late reply Julian, I completely forgot to check my post here!

To answer you, nope, I didn't create any palette or started the app twice... Hope it still help and relevant after 20 days...

**Comment by juliandescottes** [comment] 2015-03-28 04:43
Yes it helps, I have not investigated the issue yet.

Thanks !

**Comment by juliandescottes** [comment] 2015-04-13 11:30
Fixed with commit d1b12a0

**Closed by juliandescottes** 2015-04-13 11:30 UTC
Labels: issue
