### ISSUE TITLE
Exporting square spritesheets

### ISSUE THREAD

**Issue by karmkroks** [juliandescottes/piskel#436] opened 2016-03-29 17:24 UTC
I'm using unity to make a 2d game and for some reason I can't import sprites from long spritesheets.

**Comment by islemaster** [comment] 2016-03-31 22:09
Would #293 "Export as PNG with X frames per row" do what you need?

**Comment by juliandescottes** [comment] 2016-05-23 21:33
Closing as duplicate of #293

**Closed by juliandescottes** 2016-05-23 21:33 UTC
