### ISSUE TITLE
Import an image to a new frame without deleting the rest of the frames

### ISSUE THREAD

**Issue by AgentGroove** [juliandescottes/piskel#294] opened 2015-08-19 18:13 UTC
I do not seem to be able to load a new image to a new frame with out deleting the original image on the other frame. Currently I am clicking on "+ Add new frame" then "Import" then loading the image. That gives me "Import as single image" and "Import as spritesheet". However clicking "Import" says "This will erase your current Piskel. Continue?"

How do I import WITHOUT erasing my current piskel?

Thank you

**Comment by juliandescottes** [comment] 2015-08-20 06:22
Hi !

If you want to import a new animation (spritesheet, or gif, or piskel) the problem is a bit complex. I talk about it in this comment https://github.com/juliandescottes/piskel/issues/285#issuecomment-109729785.

If you just want to import a static image (png, bmp), you should be able to drag and drop it in your canvas directly. !! It needs to be smaller than your canvas resolution, because it will not be resized !!

Let me know if this helps, otherwise give me more details about what you're trying to do :)

**Comment by juliandescottes** [comment] 2016-12-09 01:18
No updates from logger, duplicate from #285 
Closing.

**Closed by juliandescottes** 2016-12-09 01:18 UTC
