### ISSUE TITLE
Chrome Memory Crash?!

### ISSUE THREAD

**Issue by AsterTehTem** [juliandescottes/piskel#561] opened 2016-11-15 01:33 UTC
So, i was making an Undertale Battle sprite, good, good. And RIGHT when i was going to save... BAM!!! THE PAGE FREAKING RELOADS WITH CHROME SAYING SOMETHING LIKE,"OH DUR DEE DUR WE RESET THE PAGE YOU WERE ON BECAUSE THERE WAS TOO MUCH MEMORY" OR SOMETHING LIKE THAT. So. I was like,"Its cool, its cool." Until... ALL OF MY WORK WAS GONE. I was left staring at a blank canvas of what all of my hard work was... Just vanished... Like that... I WAS FREAKING IN 
T E A R S BECAUSE I WAS WORKING SOOOOOOO HARD ON THAT ONE PICTURE. JUST... BAM! GONE. Please... Please fix this... And if there is a way to recover my work, i will do all that i can to get that picture back... Please... Please please please... I am freaking desperately searching for anyone else who had this problem and nothing. Please... Fix this. And if there is a way, please help me recover my work!...

**Comment by juliandescottes** [comment] 2016-11-15 08:19
I am really sorry about that :( 

Unfortunately, if you didn't save your progress at any point I don't have any way to restore your sprite. 
There is a one-shot recovery tool in the import panel:
![image](https://cloud.githubusercontent.com/assets/1141550/20297953/8683d452-ab13-11e6-8a52-15d008e96f35.png)

But if you already made a new sprite with the application this won't work, as it only allows to restore the last edit.

If you could I'd appreciate having the specs of the sprite you were editing:
- resolution
- number of frames
- number of layers
... as well as the approximate duration of your session.

I think the issue is probably linked to the way I keep the history of edits to allow undo/redo. Everything is stored in memory, so as you edit the same sprite without reloading the page it can get too big and crash the browser. 
In the short term I think we could limit the number of stored history states. This number should depend on the specs of the sprite, because we obviously can store a lot more steps for small sprites than for bug sprites.

**Comment by juliandescottes** [comment] 2016-11-19 00:21
Sorry again about this issue, but I will close this ticket in favor of #374 where I will implement some of the fixes I mentioned here.

**Closed by juliandescottes** 2016-11-19 00:21 UTC
