### ISSUE TITLE
Import image not working on Linux desktop application

### ISSUE THREAD

**Issue by jonshouse1** [juliandescottes/piskel#419] opened 2016-03-03 17:28 UTC
I have tried everything I can think of.

I select import Image, browse to a png, it shows a preview, I select "Import" by pressing the button, nothing happens - app just seems to ignore me ?

**Comment by juliandescottes** [comment] 2016-03-03 21:59
Thanks for reporting the issue.

Can you : 
- upload the PNG you are trying to import 
- try importing in the online version (either at http://juliandescottes.github.io/piskel/ or http://piskelapp.com/p/create ) and let me know if the issue also occurs there?

Thanks!

**Comment by jonshouse1** [comment] 2016-03-04 00:23
Import works for the image on the online version.

I cant see the option to attach a file here so I have stuck the file here:
http://www.jonshouse.co.uk/ffout1301.png

The piskel binary I am using should be recent, it has the md5sum:
20846a5f9f77d2cfcdd14ef915ee5cf3  piskel

The directory the binary is in is writeable by the linux user.

Many thanks,
Jon

**Comment by juliandescottes** [comment] 2016-03-05 12:26
Just reproduced with the latest 0.6.0 on Ubuntu 14.04.4.

From my limited testing it looks like the issue is with the confirm prompt. 
All the flows using a native window.alert/confirm/prompt are not working apparently on Linux. 

Looks like this was fixed in nwjs 12.0 (see https://github.com/nwjs/nw.js/issues/2683)

For now I use nwjs 11.5 for windows and linux builds, which could explain the issue. I will update to 12.0 (or newer) when releasing 0.7.0.

Impacted features are: 
- importing image
- renaming layers
- restoring session

As a workaround you can either 

(1) use the website version 
- or - 
(2) import the image on the website, save as .piskel, import the .piskel on the offline app (phew ...)

Thanks a lot for bringing this to my attention @jonshouse1 !

**Comment by jonshouse1** [comment] 2016-03-21 10:43
It would be great to use the offline version, let me know when a new release is ready. Thanks.

**Closed** 2016-03-31 02:11 UTC
Labels: priority:2, status:confirmed, type:bug
